### ISSUE TITLE
Missing python requirement

### ISSUE THREAD

**Issue by getorca** [dalab/web2text#15]
It appears the https://pypi.org/project/future/ module is missing, or I guess there's no requirements file, or incomplete in docs... 

Command:
`$ python src/main/python/main.py classify result\step_1_extracted_features result/step_2_classified_labels`

Error:
```
Traceback (most recent call last):
  File "src/main/python/main.py", line 7, in <module>
    from forward import EDGE_VARIABLES, UNARY_VARIABLES, edge, loss, unary
  File "/home/lawrence/web2text/src/main/python/forward.py", line 4, in <module>
    from config import Config
  File "/home/lawrence/web2text/src/main/python/config.py", line 5, in <module>
    from future.utils import iteritems
ModuleNotFoundError: No module named 'future'
```

Resolution:
`$ pip install future`

**Comment by tvogels** [comment]
thanks for reporting this
